"  ▄█    █▄   ▄█    ▄▄▄▄███▄▄▄▄
" ███    ███ ███  ▄██▀▀▀███▀▀▀██▄
" ███    ███ ███▌ ███   ███   ███
" ███    ███ ███▌ ███   ███   ███
" ███    ███ ███▌ ███   ███   ███
" ███    ███ ███  ███   ███   ███
" ███    ███ ███  ███   ███   ███
"  ▀██████▀  █▀    ▀█   ███   █▀

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => General
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" 'let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'scrooloose/nerdtree'
Plugin 'bling/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'scrooloose/syntastic'
Plugin 'airblade/vim-gitgutter'
Plugin 'chriskempson/base16-vim'

" Plugin 'flazz/vim-colorschemes'
Plugin 'NLKNguyen/papercolor-theme'
Plugin 'sonph/onehalf', {'rtp': 'vim/'}

" Plugin 'Yggdroot/indentLine'
" let g:indentLine_char='|'
" let g:indentLine_color_term = 239

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

set history=500 " Set how many lines of history VIM has to remember

set autoread " detect when a file is changed

set backspace=indent,eol,start " make backspace behave in a same manner

let mapleader = "," " set a map leader for more key combos

set clipboard=unnamed

set ttyfast " faster redrawing

" code folding settings
set foldmethod=syntax " fold based on indent
set foldnestmax=10 " deepest fold is 10 levels
set nofoldenable " don't fold by default
set foldlevel=1

" :W sudo saves the file
" " (useful for handling the permission-denied error)
command W w !sudo tee % > /dev/null

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Text, tab and indent related
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" set noexpandtab " insert tabs rather than spaces for <Tab>
set expandtab " insert spaces for <Tab>
set smarttab " tab respects 'tabstop', 'shiftwidth', and 'softtabstop'
set tabstop=4 " the visible width of tabs
set softtabstop=4 " edit as if the tabs are 4 characters wide
set shiftwidth=4 " number of spaces to use for indent and unindent
set shiftround " round indent to a multiple of 'shiftwidth'

set ai "Auto indent
set si "Smart indent
set wrap "Wrap lines
" set wrapmargin=8 " wrap lines when coming within n characters from side
" set textwidth=120 " Set text wrapping
set linebreak " set soft wrapping
set showbreak=... " show ellipsis at breaking

set list
set listchars=tab:>-,trail:-
"autocmd! bufreadpost * set noexpandtab | retab! 4
"autocmd! bufwritepre * set expandtab | retab! 4
"autocmd! bufwritepost * set noexpandtab | retab! 4


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => User Interface
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set so=7 " set 7 lines to the cursors - when moving vertical

set wildmenu " enhanced command line completion
set hidden " current buffer can be put into background
set showcmd " show incomplete commands
set wildmode=list:longest " complete files like a shell

set wildignore=*.o,*~,*.pyc
if has("win16") || has("win32")
    set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,*/.DS_Store
else
    set wildignore+=.git\*,.hg\*,.svn\*
endif

set ruler " Always show current position
set title " set terminal title
set cmdheight=1 " Height of the command bar

" In many terminal emulators the mouse works just fine, thus enable it.
if has('mouse')
    set mouse=a
    set ttymouse=xterm2
endif

" Searching
set ignorecase " case insensitive searching
set smartcase " case-sensitive if expresson contains a capital letter
set hlsearch
set incsearch " set incremental search, like modern browsers
set nolazyredraw " don't redraw while executing macros

set magic " Set magic on, for regex

set showmatch " show matching braces
set mat=2 " how many tenths of a second to blink

" No annoying sound on errors
set noerrorbells
set novisualbell
set t_vb=
set tm=500

set number
set relativenumber
autocmd InsertEnter * :set norelativenumber number
autocmd InsertLeave * :set relativenumber
" set relativenumber " show relative line numbers
set cursorline
" set cursorcolumn

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Status line
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Always show the status line
set laststatus=2

" Format the status line
" set statusline=\ %{HasPaste()}%F%m%r%h\ %w\ \ CWD:\ %r%{getcwd()}%h\ \ \ Line:\ %l

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Colors and Fonts
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Enable syntax highlighting and set background
syntax enable " syntax enable keeps your color settings, syntax on overrides them

set encoding=utf-8
set fileencodings=utf-8,gbk
let &termencoding=&encoding
let base16colorspace=256
highlight Comment cterm=bold
set background=dark
set t_Co=256

" hi Normal ctermbg=NONE
colorscheme PaperColor


" Use Unix as the standard file type
set ffs=unix,dos,mac
set ff=unix

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Files, backups and undo
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Turn backup off, since most stuff is in SVN, git et.c anyway...
"set nobackup
"set nowb
"set noswapfile
"set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
"set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set backupdir=~/.vim/tmpfiles//
set directory=~/.vim/tmpfiles//

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Mappings: Fixing key in Tmux
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

if &term =~ '^screen'
" tmux will send xterm-style keys when its xterm-keys option is on
    execute "set <xUp>=\e[1;*A"
    execute "set <xDown>=\e[1;*B"
    execute "set <xRight>=\e[1;*C"
    execute "set <xLeft>=\e[1;*D"
endif

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Mappings: Visual mode related
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Visual mode pressing * or # searches for the current selection
" Super useful! From an idea by Michael Naumann
vnoremap <silent> * :call VisualSelection('f', '')<CR>
vnoremap <silent> # :call VisualSelection('b', '')<CR>

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Mappings: Moving around, tabs, windows and buffers
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
map <leader>wc :wincmd q<cr>

" moving up and down work as you would expect
nnoremap <silent> j gj
nnoremap <silent> k gk
nnoremap <silent> ^ g^
nnoremap <silent> $ g$

" Deal with multiple entries within helpgrep
nmap <RIGHT> :cnext<cr>
nmap <DOWN> :cnfile<cr>
nmap <UP> :cpfile<cr>
nmap <LEFT> :cprev<cr>


" scroll the viewport faster
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>

" Map <Space> to / (search)
map <space> /

" Disable highlight when <leader><cr> is pressed
map <silent> <leader><cr> :noh<cr>

" helpers for dealing with other people's code
nmap \t :set ts=4 sts=4 sw=4 noet<cr>
nmap \s :set ts=4 sts=4 sw=4 et<cr>

" switching tabs
map <F7> :tabprevious<cr>
map <F8> :tabnext<cr>

" moving between windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" moving between or create windows
map <C-LEFT> :call WinMove('h')<cr>
map <C-DOWN> :call WinMove('j')<cr>
map <C-UP> :call WinMove('k')<cr>
map <C-RIGHT> :call WinMove('l')<cr>

" Close the current buffer
map <leader>bd :Bclose<cr>

" Close all the buffers
map <leader>ba :bufdo bd<cr>

" Useful mappings for managing tabs
map <leader>tn :tabnew<cr>
map <leader>to :tabonly<cr>
map <leader>tc :tabclose<cr>
map <leader>tm :tabmove
map <leader>t<leader> :tabnext

" Let 'tl' toggle between this and the last accessed tab
let g:lasttab = 1
nmap <Leader>tl :exe "tabn ".g:lasttab<CR>
au TabLeave * let g:lasttab = tabpagenr()


" Opens a new tab with the current buffer's path
" Super useful when editing files in the same directory
map <leader>eo :e! <c-r>=expand("%:p:h")<cr>/
map <leader>en :tabedit <c-r>=expand("%:p:h")<cr>/
" editing files in the home directory
map <leader>eh :tabedit <c-r>=expand("~")<cr>/
map <leader>eg :tabedit <c-r>=expand("~/mfs")<cr>/

" Switch CWD to the directory of the open buffer
map <leader>cd :cd %:p:h<cr>:pwd<cr>

" Specify the behavior when switching between buffers
try
    set switchbuf=useopen,usetab,newtab
    set stal=2
catch
endtry

" switch between current and last buffer
nmap <leader>. <c-^>

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Mappings: Editing
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" map <leader>ev :e! ~/.vimrc<cr> " edit ~/.vimrc
map <leader>ev :e! ~/.vimrc<cr>
nnoremap <F9> :vsp ~/.vimrc<cr>

" Move a line of text using ALT+[jk] or Comamnd+[jk] on MobaXterm
nmap <Esc>j mz:m+<cr>`z
nmap <Esc>k mz:m-2<cr>`z
vmap <Esc>j :m'>+<cr>`<my`>mzgv`yo`z
vmap <Esc>k :m'<-2<cr>`>my`<mzgv`yo`z

" Move a line of text using Option or ALT+[jk] on Mac
if has("mac") || has("macunix")
    nmap ∆ mz:m+<cr>`z
    nmap ˚ mz:m-2<cr>`z
    vmap ∆ :m'>+<cr>`<my`>mzgv`yo`z
    vmap ˚ :m'<-2<cr>`>my`<mzgv`yo`z
endif

" enable . command in visual mode
vnoremap . :normal .<cr>

" remove extra whitespace
nmap <leader>w<leader> :%s/\s\+$<cr>

" shortcut to save
nmap <leader>, :w<cr>

" set paste toggle
set pastetoggle=<F6>

" toggle paste mode
map <leader>v :set paste!<cr>

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Spell checking
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Pressing ,ss will toggle and untoggle spell checking
map <leader>ss :setlocal spell!<cr>

" Shortcuts using <leader>
map <leader>sn ]s
map <leader>sp [s
map <leader>sa zg
map <leader>s? z=

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Misc
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Remove the Windows ^M - when the encodings gets messed up
noremap <Leader>m mmHmt:%s/<C-V><cr>//ge<cr>'tzt'm

" Quickly open a buffer for scribble
map <leader>q :e ~/buffer<cr>

" Quickly open a markdown buffer for scribble
map <leader>x :e ~/buffer.md<cr>

" Toggle paste mode on and off
map <leader>pp :setlocal paste!<cr>

" disable Ex mode
noremap Q <NOP>
noremap J gj
noremap K gk

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Functions
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Delete trailing white space on save, useful for Python and CoffeeScript ;)
func! DeleteTrailingWS()
    exe "normal mz"
    %s/\s\+$//ge
    exe "normal `z"
endfunc
autocmd BufWrite *.py :call DeleteTrailingWS()
autocmd BufWrite *.coffee :call DeleteTrailingWS()

" Window movement shortcuts
" move to the window in the direction shown, or create a new window
function! WinMove(key)
    let t:curwin = winnr()
    exec "wincmd ".a:key
    if (t:curwin == winnr())
        if (match(a:key,'[jk]'))
            wincmd v
        else
            wincmd s
        endif
        exec "wincmd ".a:key
    endif
endfunction

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Plugin settings
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" close NERDTree after a file is opened
let g:NERDTreeQuitOnOpen=1
" show hidden files in NERDTree
let NERDTreeShowHidden=1
" Toggle NERDTree
" nmap <silent> <leader>k :NERDTreeToggle<cr>
nmap <silent> <C-L> :NERDTreeToggle<CR>
" expand to the path of the file in the current buffer
nmap <silent> <leader>l :NERDTreeFind<cr>

" map fuzzyfinder (CtrlP) plugin
" nmap <silent> <leader>t :CtrlP<cr>
nmap <silent> <leader>r :CtrlPBuffer<cr>
let g:ctrlp_map='<leader>t'
let g:ctrlp_dotfiles=1
let g:ctrlp_working_path_mode = 'ra'

" CtrlP ignore patterns
let g:ctrlp_custom_ignore = {
            \ 'dir': '\.git$\|node_modules$\|\.hg$\|\.svn$',
            \ 'file': '\.exe$\|\.so$'
            \ }
" search the nearest ancestor that contains .git, .hg, .svn
let g:ctrlp_working_path_mode = 2
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#tab_nr_type = 1
let g:airline#extensions#tabline#switch_buffers_and_tabs = 1
" let g:airline_theme='luna'

" Indent Guides
" let g:indent_guides_enable_on_vim_startup = 1
" let g:indent_guides_guide_size = 1

" Auto add head info
" " .py file into add header
function HeaderPython()
    call setline(1, "#! /usr/bin/env python")
    call append(1, "# -*- coding: utf-8 -*-")
    normal G
    normal o
endf
autocmd bufnewfile *.py call HeaderPython()
